/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/identity/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap/resolve an anonymous device identity, issue a bearer token */
        post: operations["IdentityController_device_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a listing by id (attributes, media, imageUrls, status) */
        get: operations["CatalogController_getListing_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/storefronts/{id}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a storefront's category tree */
        get: operations["CatalogController_categories_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the catalog; returns a blended grid + a generation hint on a miss */
        get: operations["SearchController_doSearch_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get (or create) the active cart for the device user + storefront */
        get: operations["CartController_getCart_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a listing to the cart; recomputes totals */
        post: operations["CartController_addItem_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cart/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a cart item; recomputes totals */
        delete: operations["CartController_removeItem_v1"];
        options?: never;
        head?: never;
        /** Change a cart item's quantity (optimistic version check) */
        patch: operations["CartController_updateItem_v1"];
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the device user's orders (most recent first) */
        get: operations["OrdersController_list_v1"];
        put?: never;
        /** Place an order from the active cart (idempotent on Idempotency-Key) */
        post: operations["OrdersController_place_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order detail — vertical-agnostic display payload (polling fallback) */
        get: operations["OrdersController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an order if the machine allows it from the current state (else 409) */
        post: operations["OrdersController_cancel_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authoritative tracking snapshot + ordered event log + latestSeq */
        get: operations["OrdersController_snapshot_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE: live tracking_event frames; Last-Event-ID replay */
        get: operations["OrdersController_stream_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generation/{generationId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE: relay images.ready/images.degraded for a generation batch */
        get: operations["OrdersController_generationStream_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness/readiness probe (pings Postgres + Redis) */
        get: operations["HealthController_health_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeviceIdentityResponseDto: {
            deviceId: string;
            userId: string;
            token: {
                accessToken: string;
                /** @constant */
                tokenType: "Bearer";
                expiresInSec: number;
            };
        };
        ListingResponseDto: {
            id: string;
            verticalId: string;
            storefrontId: string;
            title: string;
            description: string;
            price: {
                amount_cents: number;
                currency: string;
            };
            /** @default {} */
            attributes: {
                [key: string]: unknown;
            };
            media: {
                /** @enum {string} */
                status: "generating_text" | "generating_media" | "ready" | "degraded";
                hero: {
                    /** Format: uri */
                    url: string;
                    /**
                     * @default image
                     * @enum {string}
                     */
                    kind: "image" | "video";
                    /** @default null */
                    blurhash: string | null;
                    /** @default 1 */
                    aspect_ratio: number;
                } | null;
                /** @default [] */
                alternates: {
                    /** Format: uri */
                    url: string;
                    /**
                     * @default image
                     * @enum {string}
                     */
                    kind: "image" | "video";
                    /** @default null */
                    blurhash: string | null;
                    /** @default 1 */
                    aspect_ratio: number;
                }[];
                /** @default null */
                expected_ready_ms: number | null;
                generation_id: string;
            };
            /** @enum {string} */
            origin: "exact_cache" | "semantic_reuse" | "seed" | "generated";
            /** @default null */
            canonicalQuery: string | null;
            /** @default null */
            embedding: number[] | null;
            /** Format: date-time */
            createdAt: string;
        };
        CategoryListResponseDto: {
            id: string;
            name: string;
            slug: string;
            parentId: string | null;
        }[];
        SearchResultDto: {
            listings: {
                id: string;
                verticalId: string;
                storefrontId: string;
                title: string;
                description: string;
                price: {
                    amount_cents: number;
                    currency: string;
                };
                /** @default {} */
                attributes: {
                    [key: string]: unknown;
                };
                media: {
                    /** @enum {string} */
                    status: "generating_text" | "generating_media" | "ready" | "degraded";
                    hero: {
                        /** Format: uri */
                        url: string;
                        /**
                         * @default image
                         * @enum {string}
                         */
                        kind: "image" | "video";
                        /** @default null */
                        blurhash: string | null;
                        /** @default 1 */
                        aspect_ratio: number;
                    } | null;
                    /** @default [] */
                    alternates: {
                        /** Format: uri */
                        url: string;
                        /**
                         * @default image
                         * @enum {string}
                         */
                        kind: "image" | "video";
                        /** @default null */
                        blurhash: string | null;
                        /** @default 1 */
                        aspect_ratio: number;
                    }[];
                    /** @default null */
                    expected_ready_ms: number | null;
                    generation_id: string;
                };
                /** @enum {string} */
                origin: "exact_cache" | "semantic_reuse" | "seed" | "generated";
                /** @default null */
                canonicalQuery: string | null;
                /** @default null */
                embedding: number[] | null;
                /** Format: date-time */
                createdAt: string;
            }[];
            /** @default null */
            generation: {
                /** @enum {string} */
                status: "pending" | "ready" | "degraded";
                canonicalQuery: string;
                generationId: string;
                pollAfterMs: number;
            } | null;
        };
        CartViewDto: {
            id: string;
            storefrontId: string;
            status: string;
            version: number;
            items: {
                id: string;
                listingId: string;
                title: string;
                qty: number;
                unitPrice: {
                    amount_cents: number;
                    currency: string;
                };
                lineTotal: {
                    amount_cents: number;
                    currency: string;
                };
            }[];
            subtotal: {
                amount_cents: number;
                currency: string;
            };
            currency: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderResponseDto: {
            id: string;
            verticalId: string;
            storefrontId: string;
            state: string;
            items: {
                id: string;
                listingId: string;
                titleSnapshot: string;
                unitPriceSnapshot: {
                    amount_cents: number;
                    currency: string;
                };
                qty: number;
            }[];
            total: {
                amount_cents: number;
                currency: string;
            };
            display: {
                stages: {
                    key: string;
                    label: string;
                    reached: boolean;
                    /** @default false */
                    current: boolean;
                }[];
                /** @enum {string} */
                trackingMode: "timeline" | "map";
            };
            capabilities: {
                /** @default false */
                liveLocation: boolean;
            };
            streamUrl: string;
            /** Format: date-time */
            placedAt: string;
        };
        OrderListResponseDto: {
            id: string;
            verticalId: string;
            storefrontId: string;
            state: string;
            items: {
                id: string;
                listingId: string;
                titleSnapshot: string;
                unitPriceSnapshot: {
                    amount_cents: number;
                    currency: string;
                };
                qty: number;
            }[];
            total: {
                amount_cents: number;
                currency: string;
            };
            display: {
                stages: {
                    key: string;
                    label: string;
                    reached: boolean;
                    /** @default false */
                    current: boolean;
                }[];
                /** @enum {string} */
                trackingMode: "timeline" | "map";
            };
            capabilities: {
                /** @default false */
                liveLocation: boolean;
            };
            streamUrl: string;
            /** Format: date-time */
            placedAt: string;
        }[];
        TrackingSnapshotResponseDto: {
            orderId: string;
            state: string;
            display: {
                stages: {
                    key: string;
                    label: string;
                    reached: boolean;
                    /** @default false */
                    current: boolean;
                }[];
                /** @enum {string} */
                trackingMode: "timeline" | "map";
            };
            events: {
                seq: number;
                /** Format: date-time */
                ts: string;
                /** @constant */
                type: "tracking_event";
                orderId: string;
                state: string;
                label: string;
                display?: {
                    stages: {
                        key: string;
                        label: string;
                        reached: boolean;
                        /** @default false */
                        current: boolean;
                    }[];
                    /** @enum {string} */
                    trackingMode: "timeline" | "map";
                };
            }[];
            latestSeq: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    IdentityController_device_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceIdentityResponseDto"];
                };
            };
        };
    };
    CatalogController_getListing_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponseDto"];
                };
            };
        };
    };
    CatalogController_categories_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponseDto"];
                };
            };
        };
    };
    SearchController_doSearch_v1: {
        parameters: {
            query: {
                storefrontId?: unknown;
                q: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultDto"];
                };
            };
        };
    };
    CartController_getCart_v1: {
        parameters: {
            query?: {
                storefrontId?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartViewDto"];
                };
            };
        };
    };
    CartController_addItem_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartViewDto"];
                };
            };
        };
    };
    CartController_removeItem_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartViewDto"];
                };
            };
        };
    };
    CartController_updateItem_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartViewDto"];
                };
            };
        };
    };
    OrdersController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponseDto"];
                };
            };
        };
    };
    OrdersController_place_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    OrdersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    OrdersController_cancel_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    OrdersController_snapshot_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingSnapshotResponseDto"];
                };
            };
        };
    };
    OrdersController_stream_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_generationStream_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_health_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
